# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca45b7397c14d3ad87bae2c86219466663fa7073c5092e8c82b78a854c3bd155e95615f094131325f070f7b3d2342f86d7e86ce0c5a462ac8994ecb906e2e95

test:
  secret_key_base: 974b1160fd3cc82c3d20565f63cba3b83687d4527b8118bed923fe96f7a48733ac96ce29b5622db3d1dbd17bc8b1fd4fb8263c5009dcea5671a178f3326f7b8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
